[versions]
jWebGPUGroup = "com.github.xpenatan.jWebGPU"
jWebGPUSnapshot = "-SNAPSHOT"

javaMain = "1.8"
javaWeb = "17"
javaFFM = "25"

jMultiplatform = "0.1.3"
lwjgl = "3.3.4"

androidGradlePlugin = "9.1.1"
gretty = "4.1.10"

[libraries]
jMultiplatform = { module = "com.github.xpenatan:jMultiplatform", version.ref = "jMultiplatform" }
lwjglBom = { module = "org.lwjgl:lwjgl-bom", version.ref = "lwjgl" }
lwjglCore = { module = "org.lwjgl:lwjgl", version.ref = "lwjgl" }
lwjglGlfw = { module = "org.lwjgl:lwjgl-glfw", version.ref = "lwjgl" }
lwjglOpengl = { module = "org.lwjgl:lwjgl-opengl", version.ref = "lwjgl" }


jWebGPUCore = { module = "com.github.xpenatan.jWebGPU:webgpu-core", version.ref = "jWebGPUSnapshot" }
jWebGPUJni = { module = "com.github.xpenatan.jWebGPU:webgpu-jni", version.ref = "jWebGPUSnapshot" }
jWebGPUDesktopJni = { module = "com.github.xpenatan.jWebGPU:webgpu-desktop-jni", version.ref = "jWebGPUSnapshot" }
jWebGPUDesktopFFM = { module = "com.github.xpenatan.jWebGPU:webgpu-desktop-ffm", version.ref = "jWebGPUSnapshot" }
jWebGPUWeb = { module = "com.github.xpenatan.jWebGPU:webgpu-web", version.ref = "jWebGPUSnapshot" }
jWebGPUWebWasm = { module = "com.github.xpenatan.jWebGPU:webgpu-web_wasm", version.ref = "jWebGPUSnapshot" }
jWebGPUAndroidWgpu = { module = "com.github.xpenatan.jWebGPU:webgpu-android-wgpu", version.ref = "jWebGPUSnapshot" }
jWebGPUAndroidDawn = { module = "com.github.xpenatan.jWebGPU:webgpu-android-dawn", version.ref = "jWebGPUSnapshot" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
gretty = { id = "org.gretty", version.ref = "gretty" }
